//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingRoomReservApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetRoomReserved
    {
        public int ResvID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> EmpID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Location Location { get; set; }
        public virtual MeetingRoom MeetingRoom { get; set; }
    }
}
