//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingRoomReservApp
{
    using System;
    
    public partial class usp_GetMeetingRoomReserv_Result1
    {
        public string RoomName { get; set; }
        public int ResvID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> NoofAttendees { get; set; }
    }
}
